name: windows_bluetooth_windows
description: A new flutter plugin project.
version: 1.0.0
homepage: https://github.com/SomeoneAndNoone/windows_bluetooth_windows
repository: https://github.com/SomeoneAndNoone/windows_bluetooth_windows/tree/main/windows_bluetooth_windows

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WindowsBluetoothWindowsPlugin
