name: windows_bluetooth
description: BLE Libary which supports only Windows
version: 1.0.0
homepage: https://github.com/SomeoneAndNoone/windows_bluetooth
repository: https://github.com/SomeoneAndNoone/windows_bluetooth/tree/main/windows_bluetooth

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

#  windows_bluetooth_windows: ^1.0.0
  windows_bluetooth_platform_interface:
    path: ../windows_bluetooth_platform_interface
  windows_bluetooth_windows:
    path: ../windows_bluetooth_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    platforms:
      windows:
        default_package: windows_bluetooth_windows


