name: windows_bluetooth_platform_interface
description: A common platform interface for the windows_bluetooth_windows plugin.
homepage: https://github.com/SomeoneAndNoone/windows_bluetooth_windows
repository: https://github.com/SomeoneAndNoone/windows_bluetooth_windows/tree/main/windows_bluetooth_platform_interface
issue_tracker: https://github.com/SomeoneAndNoone/windows_bluetooth_windows/issues

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.10.0